
import React from 'react';
import Section from './Section';
import { KEY_NOTATIONS } from '../constants';

const WelcomeTab: React.FC = () => {
  return (
    <div className="animate-fadeIn">
      <Section title="Welcome to the F0Z Agent Simulation Explorer">
        <p className="text-gray-300 mb-4 leading-relaxed">
          This application provides an interactive environment to explore the fascinating concepts
          underpinning the F0Z framework, including its mathematical foundations, core agent behaviors,
          system-level interactions, computational agent structures, and quantum components.
        </p>
        <p className="text-gray-300 mb-4 leading-relaxed">
          Navigate through the tabs to:
        </p>
        <ul className="list-disc list-inside text-gray-300 mb-6 space-y-2 pl-4">
          <li>Understand core <strong className="text-primary-400">F0Z Mathematical Functions</strong> like stabilization.</li>
          <li>Observe a simplified <strong className="text-primary-400">Agent Simulation</strong>, including flow state adjustments and resource allocation.</li>
          <li>Review formulas related to <strong className="text-primary-400">Advanced Concepts</strong> such as Computational Agents and Quantum Components.</li>
        </ul>
        <p className="text-gray-300 mb-4 leading-relaxed">
          For many of the formulas and concepts, you can click the 
          <span className="inline-flex items-center mx-1 px-1.5 py-0.5 rounded-md bg-primary-700 text-primary-200 text-xs">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor" className="w-3 h-3 mr-1"><path strokeLinecap="round" strokeLinejoin="round" d="M11.25 11.25l.041-.02a.75.75 0 011.063.852l-.708 2.836a.75.75 0 001.063.853l.041-.021M21 12a9 9 0 11-18 0 9 9 0 0118 0zm-9-3.75h.008v.008H12v-.008z" /></svg>
            Explain
          </span>
          button to get a detailed explanation generated by Google's Gemini AI.
        </p>
         <p className="text-sm text-gray-400 italic">
          Note: The agent simulations are simplified representations for illustrative purposes. The API key for Gemini must be configured in your environment for explanations to work.
        </p>
      </Section>
      <Section title="Key Notation Summary">
        <pre className="bg-gray-900 p-4 rounded-md text-gray-300 text-sm whitespace-pre-wrap overflow-x-auto">
          {KEY_NOTATIONS.trim()}
        </pre>
      </Section>
    </div>
  );
};

export default WelcomeTab;
